openapi: 3.1.0
x-stoplight:
  id: 9g6byh3ir5vrc
info:
  title: petstore
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /pet:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
      operationId: get-pets
    post:
      summary: ''
      operationId: post-pets
      responses:
        '200':
          description: OK
        '':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
    parameters: []
components:
  schemas:
    Pet:
      title: Pet
      x-stoplight:
        id: 78u5wz1ehhtq6
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        '':
          type: string
