# This is an workflow to autmaticly tests the validity of your OAS definitons and the Common Gateway's abillity to provide an API for them

name: Automated Testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] 
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Uses the default testing workflow from https://github.com/CommonGateway/workflows 
jobs:
  call-testing-workflow-from-default-workflows:
    uses: CommonGateway/workflows/.github/workflows/tests.yml@main